<h1>Introduction to Notebooks<h1>

In [2]:
def check_movie_release(movie):
    if movie['release_year'] < 2000:
        print(f"{movie['name']} was released before 2000")
    else:
        print(f"{movie['name']} was released after 2000")
        return movie['name']

recent_movies = []

favorite_movies =[
    {
        "name": "The Matrix IV",
        "release_year": 2022,
        "sequels": ["The Matrix I", "The Matrix II", "The Matrix III"]
    },
    {
        "name": "Star Wars IV",
        "release_year": 1977,
        "sequels": ["Star Wars V", "Star Wars VI", "Star Wars VII", "Star Wars VIII", "Star Wars IX"],
        "prequels": ["Star Wars I", "Star Wars II", "Star Wars III"]
    },
    {
        "name": "The Lord of the Rings: The Fellowship of the Ring",
        "release_year": 2001,
        "sequels": ["The Two Towers", "The Return of the King"]
    }
]

for movie in favorite_movies:
    updated_movie = updated_check_movie_release(movie, 2020)
    if updated_movie['recent']:
        recent_movies.append(updated_movie['name'])

print(recent_movies)

NameError: name 'updated_check_movie_release' is not defined

In [ ]:
def updated_check_movie_release(movie, released_after_year, released_before_year=2024):
    if released_after_year < movie['release_year'] and movie['release_year'] < released_before_year:
        movie['recent'] = True
    else:
        movie['recent'] = False
    return movie

In [1]:
import pandas as pd

pd.__version__

'2.2.1'

In [6]:
film_scripts = pd.read_csv('cleaned_pudding_data.csv')

In [7]:
film_scripts

,imdb_id,script_id,title,year,gross (inflation-adjusted),link
0,tt0023622,5154,Trouble in Paradise,1932,NaN,http://www.aellea.com/emruf3/tip.html
1,tt0024368,4677,Mystery of the Wax Museum,1933,NaN,http://www.aellea.com/script/qWAX.htm
2,tt0025905,5147,Transatlantic Merry-Go-Round,1934,NaN,http://www.aellea.com/emruf3/tm.html
3,tt0031679,4658,Mr. Smith Goes to Washington,1939,NaN,http://www.dailyscript.com/scripts/Mr%20Smith%...
4,tt0031725,3016,Ninotchka,1939,45.0,http://www.dailyscript.com/scripts/Ninotchka.txt
...,...,...,...,...,...,...
119,tt0366627,2651,The Jacket,2005,8.0,http://www.dailyscript.com/scripts/The_Jacket....
120,tt0372532,4992,The Wedding Date,2005,42.0,http://www.dailyscript.com/scripts/somethingbo...
121,tt0416658,4034,Crazylove,2005,NaN,http://www.dailyscript.com/scripts/crazy_love....
122,tt0421054,4121,Domino,2005,13.0,http://www.dailyscript.com/scripts/domino.html
123,tt0480249,4392,I Am Legend,2007,323.0,http://www.horrorlair.com/scripts/legend.txt